로또 기능 구현 완료
SOPT32-Effective-Java-Study/choiseungjun-java-lotto pull request #1
Opened 2023-06-04 12:10 UTC by PgmJun

2023-06-16 13:17 UTC, ditoo-land commented on docs/README.md
> +
기능 목록 꼼꼼하게 잘 적어주셨네요!

2023-06-16 13:18 UTC, ditoo-land commented on docs/README.md
> +- [ ] Lotto의 패키지 변경은 가능하다.
완료한 체크리스트는 체크하면 좋을 것 같습니다:)

2023-06-16 13:22 UTC, ditoo-land commented on src/main/java/lotto/config/AppConfig.java
> +    private static final LottoService lottoService = lottoService();
static으로 두었을 때와 인스턴스를 생성했을 때와 어떤 차이가 있을까요?
static으로 둔다는 것은 상수로 취급한다는 것인데, 정말 view와 controller, service가 절대 바뀔 일이 없을까요?

2023-06-16 13:23 UTC, ditoo-land commented on src/main/java/lotto/constant/ConsoleMessage.java
> +}
상수 파일을 만들 때와 만들지 않았을 때, 어떤 장단점이 있었나요?

2023-06-16 13:31 UTC, ditoo-land commented on src/main/java/lotto/controller/LottoController.java
> +    }
일급 컬렉션을 적용해보면 어떨까요?

2023-06-16 13:36 UTC, ditoo-land commented on src/main/java/lotto/controller/LottoController.java
> +            List<Integer> winningLottoNumbers = lottoService.getWinningLottoNumbers(winningLottoNumber);
string으로 되어있는 로또 숫자들을 split 해주는 역할인데 `get` 보다는 `format`이나 `change`가 더 어울릴 것 같아요.

추가적으로 당첨 로또 숫자들이 controller에서 관리되고 있네요. controller의 역할일까요?
아마 Service를 만들어서 그런 것 같아요.
당첨 로또 번호를 도메인으로 보면 어떨까요?

2023-06-16 13:36 UTC, ditoo-land commented on src/main/java/lotto/controller/LottoController.java
> +            return new Lotto((winningLottoNumbers));
괄호 두 번 있습니다!

2023-06-16 13:40 UTC, ditoo-land commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
순환 참조가 일어납니다. `LottoNumber`가 `Lotto`를 알아도 될까요?

2023-06-16 13:41 UTC, ditoo-land commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
보너스 숫자를 체크하는 것은 다른 숫자들도 봐야하기 때문에 `Lotto`가 담당하는 것이 좋지 않을까요?

2023-06-16 13:44 UTC, ditoo-land commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
indent가 요구 사항에 맞지 않습니다ㅠㅠㅠ

2023-06-16 13:46 UTC, ditoo-land commented on src/main/java/lotto/controller/LottoController.java
> +    }
`getResult()`는 어떻게 생각하시나요?

2023-06-16 13:48 UTC, ditoo-land commented on src/main/java/lotto/domain/Lotto.java
> +    }
함수에서 두가지 일을 하고 있는 것 같아요.
1. 검증
2. int -> lotto number 변환

2023-06-16 13:55 UTC, ditoo-land commented on src/main/java/lotto/domain/constant/LottoConstant.java
> +    public static String WINNING_REWARD_FORMAT = "###,###";
저는 상수 파일을 따로 관리하지 않는데요.
그러는 이유는
1. 하나의 파일로 관리하게 되면 다른 개발자와 코드 충돌 가능성을 높인다.
2. 캡슐화가 깨진다. 해당 숫자를 보기 위해 상수 파일을 다시 보아야하는 번거로움이 있다.

그래서 저는 상수는 쓰이는 객체 안에 정의하는 편입니다.
승준님의 생각은 어떠신가요?

2023-06-16 13:59 UTC, ditoo-land commented on src/main/java/lotto/domain/Money.java
> +    }
`Lotto`는 validate를 사용하는데 일반 생성자로 생성하고, `Money`는 정적 팩토리 메소드를 통해서 생성하셨는데 구분의 기준이 무엇인지 여쭈어봐도 될까요?😀

2023-06-16 14:01 UTC, ditoo-land commented on src/main/java/lotto/domain/Money.java
> +    }
생성자에서 사용되는데, 생성자 메소드랑 거리가 떨어진 느낌이 있습니다.
위의 `getAmount()` 함수를 가장 하단으로 보내면 어떨까요?

2023-06-16 14:02 UTC, ditoo-land commented on src/main/java/lotto/domain/Rank.java
> +    ;
enum 아주 좋아요!!

2023-06-16 14:05 UTC, ditoo-land commented on src/main/java/lotto/service/LottoService.java
> +    float getProfitPercentage(Map<Rank, Integer> winnings, Money money);
interface로 먼저 추상화하셨는데, 추상화 했을 때 장점은 무엇이었나요?😄

2023-06-16 14:09 UTC, ditoo-land commented on src/main/java/lotto/service/LottoServiceImpl.java
> +    }
`List<LottoNumber>` 가 아니라 `List<Integer>`로 반환하신 이유를 여쭈어봐도 괜찮을까요?

2023-06-16 14:10 UTC, ditoo-land commented on src/main/java/lotto/service/LottoServiceImpl.java
> +        }
아마 스스로도 아쉬우실 것 같은데 조금 더 고민해보시면 좋을 것 같아요!

2023-06-16 14:12 UTC, ditoo-land commented on src/main/java/lotto/service/LottoServiceImpl.java
> +    }
Optional 대신에 Rank에 NO_RANK를 만들어보는 것은 어떠신가요?

2023-06-16 14:14 UTC, ditoo-land commented on src/main/java/lotto/service/LottoServiceImpl.java
> +    }
객체지향생활체조 규칙중에 컬렉션 자료형의 이름을 넣지 않는다가 있습니다!

2023-06-17 10:56 UTC, ditoo-land commented on src/main/java/lotto/service/LottoServiceImpl.java
> +    }
마찬가지로 `Winnings`라는 객체로 두어 그 안에서 생성하고 랭크 업데이트를 시키는 것은 어떤가요?

2023-06-17 11:01 UTC, ditoo-land commented on src/main/java/lotto/service/LottoServiceImpl.java
> +            profit += rank.getReward() * winningCount;
getter를 사용하기보다 rank에서 작업하도록 하는 것은 어떠신가요?
```suggestion
            profit += rank.calculateProfit();
```

ranks 라는 일급 컬렉션을 두면 관리하기 더 편할 것 같아요:)

2023-06-17 11:03 UTC, ditoo-land commented on src/main/java/lotto/view/InputView.java
> +    private final OutputView outputView;
input에도 출력 멘트가 들어가 있어도 괜찮다고 생각해요. 
어떤 입력이 와야하는지 알려주는 용도니깐요.

그래서 다른 언어(파이썬)에서는
input("로또 번호를 입력해주세요: ")
형태로 input 메소드가 만들어져 있어요!

2023-06-17 11:05 UTC, ditoo-land requested changes
코드 작성하시는데 고생하셨습니다!
코멘트 남겼는데 확인해주세욤

2023-07-04 03:30 UTC, PgmJun commented on docs/README.md
> +- [ ] Lotto의 패키지 변경은 가능하다.
아하 확인하지 못했네요 ㅠㅠ 감사합니다!!

2023-07-04 03:30 UTC, PgmJun commented on src/main/java/lotto/config/AppConfig.java
> +    private static final LottoService lottoService = lottoService();
어라..!! 스터디원들의 의견을 적용해보는 과정에서 코드 작성한 부분을 그대로 커밋해버렸습니다..! 신경써야할 부분인데 체크하지 못하였네요 ㅠㅠ 감사합니다!

2023-07-04 03:32 UTC, PgmJun commented on src/main/java/lotto/constant/ConsoleMessage.java
> +}
상수 파일을 만들어 콘솔 메시지를 한 곳에서 관리하기 때문에
변동사항이 생길 시에 찾기 편하다는 점이 가장 큰 장점인 것 같습니다!
대신 이러한 방식으로 상수를 관리하기 위해선, 상수의 내용에 따른 분리가 확실히 이뤄져야 할 것 같습니다.
ex) 콘솔메시지, 로또 관련 상수 etc..

2023-07-04 03:46 UTC, PgmJun commented on src/main/java/lotto/controller/LottoController.java
> +            List<Integer> winningLottoNumbers = lottoService.getWinningLottoNumbers(winningLottoNumber);
@ditoo-land 
이런 상황에서 네이밍 굉장히 고민됐었는데 format이라는 네이밍 너무 좋은 것 같습니다!!! 감사합니다!

2023-07-04 03:47 UTC, PgmJun commented on src/main/java/lotto/controller/LottoController.java
> +            List<Integer> winningLottoNumbers = lottoService.getWinningLottoNumbers(winningLottoNumber);
@ditoo-land 
말씀해주신 부분에 대해서는 이런식으로 처리해보았는데 어떤가요??

**LottoController**
```
private Lotto generateWinningLotto() {
        try {
            return lottoService.getWinningLottoNumbers(inputView.readWinningLottoNumber());

        } catch (IllegalArgumentException error) {
            outputView.printError(error);
            return generateWinningLotto();
        }
    }
```

LottoServiceImpl
```
public Lotto formatWinningLotto(String winningLottoNumber) {
        try {
            List<Integer> lottoNumbers = Arrays.stream(winningLottoNumber.split(LOTTO_NUMBER_SEPARATOR))
                    .map(Integer::parseInt)
                    .collect(Collectors.toList());

            return new Lotto(lottoNumbers);

        } catch (NumberFormatException error) {
            throw new IllegalArgumentException(NUMBER_FORMAT_ERROR_MESSAGE);
        }
    }
```

2023-07-04 03:49 UTC, PgmJun commented on src/main/java/lotto/controller/LottoController.java
> +            return new Lotto((winningLottoNumbers));
@ditoo-land 
으악 이런실수를ㅠㅠㅠ!

2023-07-04 03:51 UTC, PgmJun commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
> 보너스 숫자를 체크하는 것을 일반 `LottoNumber`라는 객체가 담당하는 것이 괜찮을까요?

보너스 넘버 또한 LottoNumber에 포함된다고 생각했는데 분리하자면 할 수 있겠군요..! 확실한 분리 좋습니다!!

2023-07-04 04:50 UTC, PgmJun commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
> indent가 요구 사항에 맞지 않습니다ㅠㅠㅠ

해당 메서드의 indent가 2인 것으로 알고 있는데, 혹시 잘못되었나요!?

2023-07-04 04:52 UTC, PgmJun commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
> 순환 참조가 일어날 수 있습니다. `LottoNumber`가 `Lotto`를 알아도 될까요?

엄청난 실수를 저질러 버렸네요ㅠㅠ 감사합니다 정훈님! 순환참조가 발생하기 딱좋은 상황이군요..

2023-07-04 04:53 UTC, PgmJun commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
> indent가 요구 사항에 맞지 않습니다ㅠㅠㅠ

이부분 또한 indent가 2이기 때문에 3 미만 indent 라는 조건에 부합한다고 생각하는데 혹시 어떤 문제가 있을까요!?

2023-07-04 04:54 UTC, PgmJun commented on src/main/java/lotto/controller/LottoController.java
> +    }
> `getResult()`는 어떻게 생각하시나요?

너무 좋은 의견입니다!! 네이밍이 부족한 약점이 드러나네요 ㅠㅠㅠ

2023-07-04 04:58 UTC, PgmJun commented on src/main/java/lotto/domain/Lotto.java
> +    }
> 함수에서 두가지 일을 하고 있는 것 같아요.
> 
> 1. 검증
> 2. int -> lotto number 변환

헉 그렇네요... 분리시켜보겠습니다 ! 감사합니다!

2023-07-04 05:02 UTC, PgmJun commented on src/main/java/lotto/domain/constant/LottoConstant.java
> +    public static String WINNING_REWARD_FORMAT = "###,###";
> 저는 상수 파일을 따로 관리하지 않는데요. 그러는 이유는
> 
> 1. 하나의 파일로 관리하게 되면 다른 개발자와 코드 충돌 가능성을 높인다.
> 2. 캡슐화가 깨진다. 해당 숫자를 보기 위해 상수 파일을 다시 보아야하는 번거로움이 있다.
> 
> 그래서 저는 상수는 쓰이는 객체 안에 정의하는 편입니다. 승준님의 생각은 어떠신가요?

도메인 객체에 대한 상수의 경우는 도메인 객체 내에서 관리하게 되면 코드가 길어지고 보기 좋지 않다는 생각에 분리를 해왔는데요!
캡슐화가 깨진다, 충돌 가능성을 높인다, 상수를 확인하기 위해 상수 클래스로 이동해야하는 것이 번거롭다는 의견에 모두 공감하고 동의합니다!
뿐만 아니라 위에서 리뷰 남겨주신 콘솔 메시지의 경우도 OutputView 클래스를 통해 관리하는 방식을 채택해보아야겠네요!
좋은 리뷰 감사합니다 정훈님!

2023-07-04 06:28 UTC, PgmJun commented on src/main/java/lotto/domain/Money.java
> +    }
> `Lotto`는 validate를 사용하는데 일반 생성자로 생성하고, `Money`는 정적 팩토리 메소드를 통해서 생성하셨는데 구분의 기준이 무엇인지 여쭈어봐도 될까요?😀

@ditoo-land 
정적 팩토리 메서드는 생성자의 접근 제어자를 private으로 변경하여 new 키워드를 통한 인스턴스 생성을 제한하는 것으로 알고 있었습니다!
하지만 배민에서 제공하는 Test Case 를 확인하면 new 키워드를 사용하여 Lotto의 인스턴스를 생성하고 있기 때문에 적용하지 않았습니다.

그런데 정훈님 말씀을 듣고 다시 한 번 찾아보니, 정적 팩터리 메서드 적용 시 생성자의 접근을 private로 막는 이유는 이미 만들어진 인스턴스를 반환하는 경우에만 해당하는 것 같네요..!
때문에 Lotto에 정적 팩터리 메서드를 적용하고 생성자 또한 public으로 남겨둘까 하는데 정훈님 생각이 궁금합니다!

2023-07-04 06:30 UTC, PgmJun commented on src/main/java/lotto/domain/Money.java
> +    }
> 생성자에서 사용되는데, 생성자 메소드랑 거리가 떨어진 느낌이 있습니다. 위의 `getAmount()` 함수를 가장 하단으로 보내면 어떨까요?

동의하는 부분입니다! 캐치하지 못한 부분 하나하나 점검해주셔서 감사합니다 ㅠㅠ

2023-07-04 06:33 UTC, PgmJun commented on src/main/java/lotto/service/LottoService.java
> +    float getProfitPercentage(Map<Rank, Integer> winnings, Money money);
> interface로 먼저 추상화하셨는데, 추상화 했을 때 장점은 무엇이었나요?😄

우선 가장 간단한 장점은 필요한 기능에 대해 미리 정리할 수 있었습니다!
그리고 지금 당장에는 도움이 되지 않았지만 스터디 시간에 함께 대화를 나누었던 것처럼
인터페이스로 분리해둔다면, 추후에 다른 로또를 도입하게 되는 상황에서도 정해져있는 틀인 인터페이스를 상속받아 편하게 구현할 수 있을 것이라고 생각이 드네요!
그렇게 되려면 Lotto 객체 또한 interface로 변경해야하고, LottoService 또한 더욱 정교하게 메서드를 설계해야겠지만요..!

2023-07-04 06:37 UTC, PgmJun commented on src/main/java/lotto/service/LottoServiceImpl.java
> +    }
> `List<LottoNumber>` 가 아니라 `List<Integer>`로 반환하신 이유를 여쭈어봐도 괜찮을까요?

이 부분은 Controller와 Service Layer의 역할 분리가 잘못되어 발생한 문제로 위측 코드 리뷰를 확인하는 과정에서 수정하였습니다 감사합니다!

2023-07-04 07:13 UTC, PgmJun commented on src/main/java/lotto/view/InputView.java
> +    private final OutputView outputView;
> input에도 출력 멘트가 들어가 있어도 괜찮다고 생각해요. 어떤 입력이 와야하는지 알려주는 용도니깐요.
> 
> 그래서 다른 언어(파이썬)에서는 input("로또 번호를 입력해주세요: ") 형태로 input 메소드가 만들어져 있어요!

오호 좋은 의견 감사합니다!!!!

2023-07-04 07:14 UTC, PgmJun commented on src/main/java/lotto/service/LottoServiceImpl.java
> +            profit += rank.getReward() * winningCount;
> getter를 사용하기보다 rank에서 작업하도록 하는 것은 어떠신가요?

정말 좋은 의견입니다!!!!! 감사합니다!

2023-07-04 07:14 UTC, PgmJun commented on src/main/java/lotto/service/LottoServiceImpl.java
> +            profit += rank.getReward() * winningCount;
> ranks 라는 일급 컬렉션을 두면 관리하기 더 편할 것 같아요:)
일급 컬렉션이 필요한 부분의 꽤 있네요!! 한번 적용해보도록 하겠습니다 감사합니다!

2024-08-01 05:58 UTC, merged